#端口
server:
  port: 8083
spring:
  profiles:
    active: dev
#单点登录服务地址
sso:
  server: 192.168.158.168:8087
---
server:
  port: 8084
spring:
  profiles: prod

---
server:
  port: 8085
spring:
  profiles: test
