#端口
server:
  port: 8080
spring:
  profiles:
    active: prod
#单点登录服务地址
sso:
  server: 192.168.158.168:8087
---
server:
  port: 8081
spring:
  profiles: prod

---
server:
  port: 8082
spring:
  profiles: test
